### PR TITLE
Issue 52

### LINKED ISSUE #52: BUG -- Requiring `name` argument in `StackAPI` makes "/users/{id}/network-activity" endpoint inaccessible
# MREs
While trying to access the "/users/{id}/network-activity" endpoint I ran into a `StackAPIError`.

```python
from stackapi import StackAPI

my_acct_id = 8698988

# Providing `name` argument raises `StackAPIError`.
SITE = StackAPI(name="stackoverflow")
SITE.fetch(endpoint="users/{id}/network-activity", id=my_acct_id)
```
```python-traceback
---------------------------------------------------------------------------
StackAPIError                             Traceback (most recent call last)
Cell In[6], line 3
      1 # Providing `name` argument raises `StackAPIError`.
      2 SITE = StackAPI(name="stackoverflow")
----> 3 SITE.fetch(endpoint="users/{id}/network-activity", id=8698988)

File ~\.env\Lib\site-packages\stackapi\stackapi.py:211, in StackAPI.fetch(self, endpoint, page, key, filter, **kwargs)
    209     code = response["error_name"]
    210     message = response["error_message"]
--> 211     raise StackAPIError(self._previous_call, error, code, message)
    212 except KeyError:
    213     pass  # This means there is no error

StackAPIError: ('https://api.stackexchange.com/2.3/users/8698988/network-activity/?pagesize=100&page=1&filter=default&site=stackoverflow', 400, 'bad_parameter', 'This method does not accept a `site` parameter')
```

After reading the [*Usage of /users/{id}/network-activity*](https://api.stackexchange.com/docs/users-network-activity) page, the error made more sense—I shouldn't supply a `site` parameter to the URL. I took this to mean not setting the `name` argument in `StackAPI`, but this raises a `ValueError`.

```python
# No site provided raises ValueError.
SITE = StackAPI()
SITE.fetch(endpoint="users/{id}/network-activity", id=my_acct_id)
```
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 6
      3 my_acct_id = 8698988
      5 # No site provided raises ValueError.
----> 6 SITE = StackAPI()
      7 SITE.fetch(endpoint="users/{id}/network-activity", id=my_acct_id)

File ~\.env\Lib\site-packages\stackapi\stackapi.py:60, in StackAPI.__init__(self, name, version, base_url, **kwargs)
     32 """
     33 The object used to interact with the Stack Exchange API
     34 
   (...)
     57     a user, to grant more permissions (such as write access)
     58 """
     59 if not name:
---> 60     raise ValueError("No Site Name provided")
     62 self.proxy = kwargs.get("proxy", None)
     63 self.max_pages = kwargs.get("max_pages", 5)

ValueError: No Site Name provided
```

# Proposal
I believe this may be an unintended bug, and if so I'd be willing to submit a PR.

# Version Info
### Python
```text
3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
```

### StackAPI
```text
Name: StackAPI
Version: 0.3.0
Summary: Library for interacting with the Stack Exchange API
Home-page: https://github.com/AWegnerGitHub/StackAPI
Author: Andrew Wegner
Author-email: pypi@andrewwegner.com
License: MIT
Location: ~\.env\Lib\site-packages
Requires: requests, six
Required-by: 
```

### PR DESCRIPTION
**Pull request by it176131**
Fixes #52

### CODE REVIEW

**Comment by it176131** [comment]
@AWegnerGitHub I await your review 🙇

**Comment by AWegnerGitHub** [comment]
Acknowledging that I've seen this @it176131 . I won't have time to review it until the weekend is over. Give me a day or two please.

**Comment by it176131** [comment]
Hey @AWegnerGitHub! Anything I can do to assist further?

**Comment by it176131** [comment]
@AWegnerGitHub 🫵

**Comment by AWegnerGitHub** [comment]
@it176131 Sorry for the delay! This has been merged and released. https://pypi.org/project/StackAPI/0.3.1/

Thank you for the PR!

**Comment by it176131** [comment]
> @it176131 Sorry for the delay! This has been merged and released. https://pypi.org/project/StackAPI/0.3.1/
> 
> Thank you for the PR! 

Woohoo! 🎉

**Pull request merged**
